Caesar Cipher

In [1]:
x = input("Enter any word \n")
odd = [90,89,88,122,121,120]
list2 = [ord(c) for c in x]
list3 = []
list4 = []
for x in list2:
    if x in odd: 
        list3.append(x+3-26)
    else:
        list3.append(x+3)
    
for x in list3:
    list4.append(chr(x))

print("\nCipher Text")    
print(''.join(list4))

Enter any word 
HELLO

Cipher Text
KHOOR


In [2]:
x = input("Enter any word: ")
key = int(input("Enter Key: "))
odd = [90,89,88,122,121,120]
list2 = [ord(c) for c in x]
list3 = []
list4 = []

assert key <26 , "Invalid key entered"

for x in list2:
    if x in odd: 
        list3.append(x+key-26)
    else:
        list3.append(x+key)
    
for x in list3:
    list4.append(chr(x))

print("\nCipher Text")    
print(''.join(list4))

Enter any word: HELLO
Enter Key: 5

Cipher Text
MJQQT


Mono-alphabetic Cipher

In [4]:
x = input("Enter any word: ")
ma = {'a':'K','b':'D','c':'G','d':'F','e':'N','f':'S','g':'L','h':'V','i':'B','j':'W','k':'A','l':'H','m':'E','n':'X','o':'J','p':'M','q':'C','r':'Q','s':'P','t':'Z','u':'R','v':'T','w':'Y','x':'I','y':'U','z':'O'}
list1 = [a for a in x.lower()]
list2 = []
for x in list1:
    list2.append(ma[x])
print(''.join(list2))

Enter any word: MORNING
EJQXBXL


WAP to implement poly alphabetic cipher

In [1]:
from numpy import *
fulllist = []
cipherlist = []
list1 = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']
fulllist.append(list1)
list2 = list1.copy()
for x in range(0,25):
    list2.append(list2[0])
    del list2[0]
    fulllist.append(list2)
    list2 = list2.copy()
print(reshape(fulllist,(26,26)))

txt = input("Enter the Plain Text: ")
txt_len = len(txt)
txtlist = [x for x in txt]
key = input("Enter The Key: ")
key_len = len(key)
keylist = [x for x in key]

if key_len<txt_len:
    i = 0
    for k in range (0,(txt_len-key_len)):
        keylist.append(key[i])
        i = i + 1
        if i == key_len:
            i = 0
else:
    print("Key Is Longer Than Plain Text")

i = 0
for j in txtlist:
    if j == ' ':
        cipherlist.append(' ')
    else:
        for k in keylist:
            cipherlist.append(fulllist[ord(j.lower())-97][ord(k.lower())-97])
            break
        
print("\nYour Key: ", ''.join(keylist))
print("\nCipher Text")
print(''.join(cipherlist))

[['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J' 'K' 'L' 'M' 'N' 'O' 'P' 'Q' 'R'
  'S' 'T' 'U' 'V' 'W' 'X' 'Y' 'Z']
 ['B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J' 'K' 'L' 'M' 'N' 'O' 'P' 'Q' 'R' 'S'
  'T' 'U' 'V' 'W' 'X' 'Y' 'Z' 'A']
 ['C' 'D' 'E' 'F' 'G' 'H' 'I' 'J' 'K' 'L' 'M' 'N' 'O' 'P' 'Q' 'R' 'S' 'T'
  'U' 'V' 'W' 'X' 'Y' 'Z' 'A' 'B']
 ['D' 'E' 'F' 'G' 'H' 'I' 'J' 'K' 'L' 'M' 'N' 'O' 'P' 'Q' 'R' 'S' 'T' 'U'
  'V' 'W' 'X' 'Y' 'Z' 'A' 'B' 'C']
 ['E' 'F' 'G' 'H' 'I' 'J' 'K' 'L' 'M' 'N' 'O' 'P' 'Q' 'R' 'S' 'T' 'U' 'V'
  'W' 'X' 'Y' 'Z' 'A' 'B' 'C' 'D']
 ['F' 'G' 'H' 'I' 'J' 'K' 'L' 'M' 'N' 'O' 'P' 'Q' 'R' 'S' 'T' 'U' 'V' 'W'
  'X' 'Y' 'Z' 'A' 'B' 'C' 'D' 'E']
 ['G' 'H' 'I' 'J' 'K' 'L' 'M' 'N' 'O' 'P' 'Q' 'R' 'S' 'T' 'U' 'V' 'W' 'X'
  'Y' 'Z' 'A' 'B' 'C' 'D' 'E' 'F']
 ['H' 'I' 'J' 'K' 'L' 'M' 'N' 'O' 'P' 'Q' 'R' 'S' 'T' 'U' 'V' 'W' 'X' 'Y'
  'Z' 'A' 'B' 'C' 'D' 'E' 'F' 'G']
 ['I' 'J' 'K' 'L' 'M' 'N' 'O' 'P' 'Q' 'R' 'S' 'T' 'U' 'V' 'W' 'X' 'Y' 'Z'
  'A' 'B' 'C' 'D' 'E' 'F' 'G' 'H']
 ['J' 'K' 'L' 'M' '

WAP to implement Hill Cipher (Plain Text = 3 Letters) GYBNQKURP

In [40]:
from numpy import *
text1 = str(input("Enter Plain Text of Lenght 3: "))
text1_list = [(ord(x.lower())-97) for x in text1]
array1 = array(text1_list)

text2 = str(input("\nInput Key of Lenght 9: "))
matrix = [(ord(x.lower()))-97 for x in text2]
array2 = reshape(matrix,(3,3))

print("\n")
print(array1)
print("\n")
print(array2)

array3 = []
for y in range(0,3):
    i = 0
    sum = 0
    sum += array2[y][i]*array1[i]
    i += 1
    sum += array2[y][i]*array1[i]
    i+= 1
    sum += array2[y][i]*array1[i]
    array3.append(sum)

array3 = array3.copy()
array4 = [chr((x%26)+65) for x in array3]
''.join(array4)

Enter Plain Text of Lenght 3: ACT

Input Key of Lenght 9: GYBNQKURP


[ 0  2 19]


[[ 6 24  1]
 [13 16 10]
 [20 17 15]]


'POH'

Implement Play-fair cipher

playfair example
Hide the gold in the tree stump

In [39]:
import numpy as np
import pandas as pd

key = str(input("Enter the key: "))
key_list = [x.upper() for x in key if x!=' ']
key_unique_list = pd.unique(key_list)
key_list2 = key_unique_list.tolist()
alphabet_list = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']

for i in alphabet_list:
    if i not in key_list2 :
        key_list2.append(i)
if 'J' in key_list2:
    key_list2.remove('J')
array = np.reshape(key_list2,(5,5))
print(array)

plain_text = str(input("Enter the Plain Text: "))
pt_list = [x.upper() for x in plain_text if x!=' ']
for i in range(len(pt_list)):
    if pt_list[i] == 'J':
        pt_list[i] = 'I'
pt_list_pair = []
temp = []
extratemp = 'null'
for i in pt_list:
    temp.append(i)
    if len(temp) == 2:
        if temp[0] == temp[1]:
            extratemp = str(temp[1])
            temp[1] = 'X'
        pt_list_pair.append(''.join(temp))
        if extratemp == temp[0]:
            temp.clear()
            temp.append(extratemp)
            extratemp = 'null'
        else:
            temp.clear()
print(pt_list_pair)

result = []    
for i in pt_list_pair:
    val1 = np.where(array == i[0])
    val2 = np.where(array == i[1])
    
    num1 = int(val1[0])
    num2 = int(val1[1])
    num3 = int(val2[0])
    num4 = int(val2[1])
    
    if int(val1[0]) != int(val2[0]) and int(val1[1]) != int(val2[1]):
        #Either of the columns lies in the middle
        if int(val1[1]) == 2:
            num2 = num4
            num4 = 2
        elif int(val2[1]) == 2:
            num4 = num2
            num2 = 2
               
        if int(val1[1]) > 2:
            if int(val2[1]) < 2:
                diff = num2 - 2
                num2 = 2 - diff
        elif int(val1[1]) < 2:
            if int(val2[1]) > 2:
                diff = 2 - num2
                num2 = 2 + diff
        if int(val2[1]) > 2:
            if int(val1[1]) < 2:
                diff = num4 - 2
                num4 = 2 - diff
        elif int(val2[1]) < 2:
            if int(val1[1]) > 2:
                diff = 2 - num4
                num4 = 2 + diff
        
        if int(val1[1]) > 2:
            if int(val2[1]) > 2:
                temp = num2
                num2 = num4
                num4 = temp
        elif int(val1[1]) < 2:
            if int(val2[1]) < 2:
                temp = num2
                num2 = num4
                num4 = temp
        
    elif int(val1[0]) == int(val2[0]):
        if num2 < 4:
            if num4 < 4:
                num2 = num2 + 1
                num4 = num4 + 1
            else:
                num4 = 0
        else:
            num2 = 0
            if num4 < 4:
                num4 = num4 + 1
            else:
                num4 = 0
        
    elif int(val1[1]) == int(val2[1]):
        if num1 < 4:
            if num3 < 4:
                num1 = num1 + 1
                num3 = num3 + 1
            else:
                num3 = 0
        else:
            num1 = 0
            if num3 < 4:
                num3 = num3 + 1
            else:
                num3 = 0
                
    result.append(array[num1][num2]+array[num3][num4])
    
print(result)
print("Cipher Text: ")
print(''.join(result))

Enter the key: playfair example
[['P' 'L' 'A' 'Y' 'F']
 ['I' 'R' 'E' 'X' 'M']
 ['B' 'C' 'D' 'G' 'H']
 ['K' 'N' 'O' 'Q' 'S']
 ['T' 'U' 'V' 'W' 'Z']]
Enter the Plain Text: Hide the gold in the tree stump
['HI', 'DE', 'TH', 'EG', 'OL', 'DI', 'NT', 'HE', 'TR', 'EX', 'ES', 'TU', 'MP']
['BM', 'OD', 'ZB', 'XD', 'NA', 'BE', 'KU', 'DM', 'UI', 'XM', 'MO', 'UV', 'IF']
Cipher Text: 
BMODZBXDNABEKUDMUIXMMOUVIF


Rail-Fence Cipher

In [34]:
import numpy as np

plain_text = "attack postponed until two am xyz"
mylist = [x for x in plain_text if x != " "]
key_seq = 4312567
mylist2 = [x for x in str(key_seq)]
i1 = int(len(mylist))
j1 = int(len(str(key_seq)))
k1 = int(i1/j1)
new_matrix = np.reshape(mylist,(k1,j1)) 
print(new_matrix)

k=0
temp = ""
new_mylist = []
for k in range(0,j1):
    for j in range(0,k1):
        temp = temp + new_matrix[j][k]
    new_mylist.append(temp)
    temp = ""

print(new_mylist)

print("\nCipher Text")
cipher = dict(zip(mylist2,new_mylist))

string = ""
for q in range(1,8):
    string = string + cipher[str(q)]
    
print(string)

[['a' 't' 't' 'a' 'c' 'k' 'p']
 ['o' 's' 't' 'p' 'o' 'n' 'e']
 ['d' 'u' 'n' 't' 'i' 'l' 't']
 ['w' 'o' 'a' 'm' 'x' 'y' 'z']]
['aodw', 'tsuo', 'ttna', 'aptm', 'coix', 'knly', 'petz']

Cipher Text
ttnaaptmtsuoaodwcoixknlypetz
